// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetClaudeStats(arg1:string):Promise<models.DashboardData>;

export function Greet(arg1:string):Promise<string>;

export function SelecionarArquivo():Promise<string>;
